# MENU
1.	Multiplication of two given matrixes 
2.	Sum of the diagonal elements of a given Matrix 
3.	Element-wise Matrix Multiplication (Hadamard Product)
4.	Outer product of two given vectors
5.	Determinant of a given square matrix

Additional set of exercises:

1.	Write a program to find the maximum and minimum from a given vector. Your implementation should be computationally efficient. 
2.	Can we think of a program to find all linearly independent vectors from a set of N, d-dimensional vectors?


# Functions

In [72]:
import numpy as np
import sympy

In [16]:
a = [[1,2],[3,4]]
b = [[1,2],[3,4]]

In [10]:
def transpose(mat):
    return [[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]

In [14]:
def matrix_multiplication(mat1,mat2):
    if len(mat1[0])!=len(mat2):
        raise Exception("Matrices can't be multiplied")
    else:
        mat2 = transpose(mat2)
        mat = list()
        for i in range(len(mat1)):
            row = []
            for j in range(len(mat2)):
                val = sum(list(map(lambda a,b:a*b,mat1[i],mat2[j])))
                row.append(val)
            mat.append(row)
        return mat                

In [41]:
def trace(mat):
    if len(mat[0]) != len(mat):
        raise Exception("Enter a square matrix")
    else:
        return sum([mat[i][i] for i in range(len(mat))])

In [12]:
def hadamard_product(mat1,mat2):
    if len(mat1) != len(mat2) or len(mat1[0]) != len(mat2[0]):
        raise Exception("Matrices can't be multiplied")
    else:
        mat = list()
        for i in range(len(mat1)):
            mat.append(list(map(lambda a,b:a*b,mat1[i],mat2[i])))
        return mat

In [69]:
def outer_vector(v1,v2):
    mat = list()
    for i in range(len(v1)):
        mat.append([v1[i]*v2[j] for j in range(len(v2))])
    return mat

# RUN

In [17]:
print("1. Multiplication of given matrixes :\n",    matrix_multiplication(a,b))
print("\n2. Trace of given matrix A :\t",           trace(a))
print("   Trace of given matrix A :\t",             trace(b))
print("\n3. Element-wise Matrix Multiplication (Hadamard Product) :\n",hadamard_product(a,b))
print("\n4. Outer Product :\n",                     outer_vector([7,3,2,1],[3,2,1]))
print("\n5. Determinant of matrix A :\t",           np.linalg.det(a))
print("   Determinant of matrix B :\t",             np.linalg.det(b))

1. Multiplication of given matrixes :
 [[7, 10], [15, 22]]

2. Trace of given matrix A :	 5
   Trace of given matrix A :	 5

3. Element-wise Matrix Multiplication (Hadamard Product) :
 [[1, 4], [9, 16]]

4. Outer Product :
 [[21, 14, 7], [9, 6, 3], [6, 4, 2], [3, 2, 1]]

5. Determinant of matrix A :	 -2.0000000000000004
   Determinant of matrix B :	 -2.0000000000000004


# Additional questions

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print("Max in the given vector: ",np.max(arr))
print("Max in the given vector: ",np.min(arr))


Max in the given vector:  5
Max in the given vector:  1


In [5]:
matrix = np.array(
    [
        [1, 0, 0, 1],
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
    ])

red_matrix, inds = sympy.Matrix(matrix).T.rref()

In [6]:
print("Independent vectors")
for i in inds:
    print(matrix[i])

Independent vectors
[1 0 0 1]
[0 1 0 0]
[0 0 1 0]
