# MENU
1.	Multiplication of two given matrixes 
2.	Sum of the diagonal elements of a given Matrix 
3.	Element-wise Matrix Multiplication (Hadamard Product)
4.	Outer product of two given vectors
5.	Determinant of a given square matrix

Additional set of exercises:

1.	Write a program to find the maximum and minimum from a given vector. Your implementation should be computationally efficient. 
2.	Can we think of a program to find all linearly independent vectors from a set of N, d-dimensional vectors?


In [1]:
import numpy as np
import sympy

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [3]:
print("1. Multiplication of given matrixes :\n",    np.dot(a,b))
print("\n2. Trace of given matrix A :\t",           np.trace(a))
print("   Trace of given matrix A :\t",             np.trace(b))
print("\n3. Element-wise Matrix Multiplication (Hadamard Product) :\n",np.multiply(a,b))
print("\n4. Outer Product :\n",                     np.outer(a,b))
print("\n5. Determinant of matrix A :\t",           np.linalg.det(a))
print("   Determinant of matrix B :\t",             np.linalg.det(b))





1. Multiplication of given matrixes :
 [[19 22]
 [43 50]]

2. Trace of given matrix A :	 5
   Trace of given matrix A :	 13

3. Element-wise Matrix Multiplication (Hadamard Product) :
 [[ 5 12]
 [21 32]]

4. Outer Product :
 [[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]

5. Determinant of matrix A :	 -2.0000000000000004
   Determinant of matrix B :	 -2.000000000000005


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print("Max in the given vector: ",np.max(arr))
print("Max in the given vector: ",np.min(arr))


Max in the given vector:  5
Max in the given vector:  1


In [5]:
matrix = np.array(
    [
        [1, 0, 0, 1],
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
    ])

red_matrix, inds = sympy.Matrix(matrix).T.rref()

In [6]:
print("Independent vectors")
for i in inds:
    print(matrix[i])

Independent vectors
[1 0 0 1]
[0 1 0 0]
[0 0 1 0]
